CREATE EXTERNAL TABLE ext_tpch.partsupp
(PS_PARTKEY BIGINT,
PS_SUPPKEY BIGINT,
PS_AVAILQTY INTEGER,
PS_SUPPLYCOST DECIMAL(15,2),
PS_COMMENT VARCHAR(199),
dummy text)
LOCATION (:LOCATION)
FORMAT 'TEXT' (DELIMITER '|' NULL AS '' ESCAPE AS E'\\');
