CREATE TABLE tpch.orders
(O_ORDERKEY BIGINT,
O_CUSTKEY BIGINT,
O_ORDERSTATUS CHAR(1),
O_TOTALPRICE DECIMAL(15,2),
O_ORDERDATE DATE,
O_ORDERPRIORITY CHAR(15), 
O_CLERK  CHAR(15), 
O_SHIPPRIORITY INTEGER,
O_COMMENT VARCHAR(79))
WITH (:LARGE_STORAGE)
:DISTRIBUTED_BY;
